name: Databricks CI/CD Deployment BikeStores 

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main

jobs:
  deploy-to-production:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Instalar Databricks CLI
    - name: Install Databricks CLI
      run: |
        pip install --upgrade databricks-cli

    # Paso 3: Configurar Databricks CLI usando variables de entorno
    - name: Set Databricks CLI environment variables
      run: |
        export DATABRICKS_HOST=${{ secrets.DATABRICKS_PROD_HOST }}
        export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_PROD_TOKEN }}

    # Paso 4: Limpiar el Workspace de Producción (opcional)
    - name: Clean production workspace
      run: |
        databricks workspace delete --path /Workspace/ProductosDatos/BikeStores --recursive --quiet || true

    # Paso 5: Desplegar notebooks y directorios al Workspace de Producción
    - name: Deploy notebooks to production
      run: |
        databricks workspace import_dir ./ /Workspace/ProductosDatos/BikeStores --overwrite

    # Paso 6: Listar contenido en Producción
    - name: List contents in production workspace
      run: |
        databricks workspace ls /Workspace/ProductosDatos/BikeStores
