name: Databricks CI/CD Deployment

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main

jobs:
  deploy-to-production:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Instalar Databricks CLI
    - name: Install Databricks CLI
      run: |
        pip install --upgrade databricks-cli

    # Paso 3: Configurar Databricks CLI mediante variables de entorno
    - name: Set environment variables for Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_PRO_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PRO_TOKEN }}
      run: echo "Environment variables set for Databricks CLI"

    # Paso 4: Limpiar el Workspace de Producción (opcional)
    - name: Clean production workspace
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_PRO_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PRO_TOKEN }}
      run: |
        databricks workspace delete --path /Workspace/ProductosDatos/BikeStores --recursive --quiet || true

    # Paso 5: Desplegar notebooks y directorios al Workspace de Producción
    - name: Deploy notebooks to production
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_PRO_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PRO_TOKEN }}
      run: |
        databricks workspace import_dir ./BikeStores/ /Workspace/ProductosDatos/BikeStores --overwrite
